### PR TITLE
ignore SIGPIPE, fix issue #1257

### LINKED ISSUE #1257: Tensorflow Serving container crashes for object detection models
## Bug Report
Tensorflow Serving 1.12 container crashes regularly when running predictions on [TensorFlow object detection models](https://github.com/tensorflow/models/blob/59f7e80ac8ad54913663a4b63ddf5a3db3689648/research/object_detection/samples/configs/ssd_inception_v3_pets.config).

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04 LTS
- **TensorFlow Serving installed from (source or binary)**: Source
- **TensorFlow Serving version**: 1.12
- **RAM**: 256 GB
- **CPU Model**: Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz
- **CPU Count**: 12

### Describe the problem

Using TensorFlow 1.9, [SSD Inception V3](https://github.com/tensorflow/models/blob/59f7e80ac8ad54913663a4b63ddf5a3db3689648/research/object_detection/samples/configs/ssd_inception_v3_pets.config) based object detection model was trained on custom dataset. Post training the model works fine without using Tensorflow Serving. When the same model is served using Tensorflow Serving, the Tensorflow serving container crashes regularly. Sometimes it crashes on first request itself and sometimes after few successful predictions. There are no concurrent requests made to Tensorflow Serving container.

If the Tensorflow Serving docker container is created using the latest code in master branch, then the container does not crash. 
* Is there any code change done after 1.12 which fixes this issue ? 
* What is the release date for next version of Tensorflow Serving ?

### Exact Steps to Reproduce

1. Train any SSD or Faster RCNN model present in [Tensorflow Research repo](https://github.com/tensorflow/models/tree/59f7e80ac8ad54913663a4b63ddf5a3db3689648/research/object_detection/samples/configs) using Tensorflow 1.9.0.
1. Build Tensorflow Serving docker image using [Dockerfile](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel)
1. Deploy the trained model in Tensorflow Serving container
1. Submit sync predictions request (`stub.Predict(request, 30.0)`) to the model served using Tensorflow Serving container.

### Source code / logs
root@vm01:~# docker run -p 9998:8500 -m 100g --cpus="6" --mount type=bind,source=$(pwd),target=/models/dev_perf_tfod_incepv3_n50_e30000 -e MODEL_NAME=dev_perf_tfod_incepv3_n50_e30000 -t custom/tensorflow-serving:1.12
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
2019-02-08 10:37:17.040097: I tensorflow_serving/model_servers/server.cc:82] Building single TensorFlow model file config:  model_name: dev_perf_tfod_incepv3_n50_e30000 model_base_path: /models/dev_perf_tfod_incepv3_n50_e30000
2019-02-08 10:37:17.040358: I tensorflow_serving/model_servers/server_core.cc:461] Adding/updating models.
2019-02-08 10:37:17.040387: I tensorflow_serving/model_servers/server_core.cc:558]  (Re-)adding model: dev_perf_tfod_incepv3_n50_e30000
2019-02-08 10:37:17.140963: I tensorflow_serving/core/basic_manager.cc:739] Successfully reserved resources to load servable {name: dev_perf_tfod_incepv3_n50_e30000 version: 1}
2019-02-08 10:37:17.141025: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: dev_perf_tfod_incepv3_n50_e30000 version: 1}
2019-02-08 10:37:17.141053: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: dev_perf_tfod_incepv3_n50_e30000 version: 1}
2019-02-08 10:37:17.141099: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:363] Attempting to load native SavedModelBundle in bundle-shim from: /models/dev_perf_tfod_incepv3_n50_e30000/1
2019-02-08 10:37:17.141126: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /models/dev_perf_tfod_incepv3_n50_e30000/1
2019-02-08 10:37:17.320294: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2019-02-08 10:37:17.456976: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:162] Restoring SavedModel bundle.
2019-02-08 10:37:17.457079: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:172] The specified SavedModel has no variables; no checkpoints were restored. File does not exist: /models/dev_perf_tfod_incepv3_n50_e30000/1/variables/variables.index
2019-02-08 10:37:17.457098: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:138] Running MainOp with key legacy_init_op on SavedModel bundle.
2019-02-08 10:37:17.457124: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:259] SavedModel load for tags { serve }; Status: success. Took 315989 microseconds.
2019-02-08 10:37:17.457162: I tensorflow_serving/servables/tensorflow/saved_model_warmup.cc:83] No warmup data file found at /models/dev_perf_tfod_incepv3_n50_e30000/1/assets.extra/tf_serving_warmup_requests
2019-02-08 10:37:17.457382: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: dev_perf_tfod_incepv3_n50_e30000 version: 1}
2019-02-08 10:37:17.462168: I tensorflow_serving/model_servers/server.cc:286] Running gRPC ModelServer at 0.0.0.0:8500 ...
[warn] getaddrinfo: address family for nodename not supported
2019-02-08 10:37:17.465124: I tensorflow_serving/model_servers/server.cc:302] Exporting HTTP/REST API at:localhost:8501 ...
[evhttp_server.cc : 237] RAW: Entering the event loop ...
double free or corruption (out)
/usr/bin/tf_serving_entrypoint.sh: line 3:     8 Aborted                 (core dumped) tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"

### PR DESCRIPTION
**Pull request by yjhjstz**
fix  #1257

### CODE REVIEW

File: tensorflow_serving/model_servers/http_server.cc [hunk 1]
```diff
@@ -180,6 +181,9 @@ class RestApiRequestDispatcher {
 std::unique_ptr<net_http::HTTPServerInterface> CreateAndStartHttpServer(
     int port, int num_threads, int timeout_in_ms,
     const MonitoringConfig& monitoring_config, ServerCore* core) {
+  // Ignore SIGPIPE and allow errors to propagate through error codes.
```
Comment (netfs) [inline tensorflow_serving/model_servers/http_server.cc]: i think this is specific to libevent. it will be good to move this closer to libevent initialization here:

https://github.com/tensorflow/serving/blob/9578f3d10c786c6714b9a8b481dd74f454402477/tensorflow_serving/util/net_http/server/internal/evhttp_server.cc#L46

**Comment by netfs** [comment]
Thanks for the PR and fix. Can you also add a more verbose commit message. #1257 was started in response to grpc crashing, not rest/http requests. and your fix is for http requests. Clarifying that in your commit message will help.

File: tensorflow_serving/model_servers/http_server.cc (hunk 1 above)
Comment (yjhjstz) [reply tensorflow_serving/model_servers/http_server.cc]: ok

**Comment by yjhjstz** [comment]
update commit , thanks.
